//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisponibiliteEspace_Client
    {
        public Nullable<int> ContratId { get; set; }
        public int EspaceId { get; set; }
        public bool Disponible { get; set; }
        public int TypeEspaceId { get; set; }
        public Nullable<int> ClientId { get; set; }
    }
}
