//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierStationnementView
    {
        public int EspaceId { get; set; }
        public string NoStationnement { get; set; }
        public bool Disponible { get; set; }
        public string Description { get; set; }
        public Nullable<int> Largeur { get; set; }
        public Nullable<int> Longueur { get; set; }
        public Nullable<decimal> Prix { get; set; }
        public string Alias { get; set; }
        public string Ville { get; set; }
    }
}
