//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IDM_DATAEntities : DbContext
    {
        public IDM_DATAEntities()
            : base("name=IDM_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<CodeElectronique> CodeElectronique { get; set; }
        public DbSet<Connexion> Connexion { get; set; }
        public DbSet<Contrat> Contrat { get; set; }
        public DbSet<Espace> Espace { get; set; }
        public DbSet<Local> Local { get; set; }
        public DbSet<Loyer> Loyer { get; set; }
        public DbSet<MethodePaiement> MethodePaiement { get; set; }
        public DbSet<Paiement> Paiement { get; set; }
        public DbSet<Site> Site { get; set; }
        public DbSet<Stationnement> Stationnement { get; set; }
        public DbSet<Taxe> Taxe { get; set; }
        public DbSet<Telephone> Telephone { get; set; }
        public DbSet<TypeEspace> TypeEspace { get; set; }
        public DbSet<Vehicule> Vehicule { get; set; }
        public DbSet<Ville> Ville { get; set; }
        public DbSet<DisponibiliteEspace_Client> DisponibiliteEspace_Client { get; set; }
        public DbSet<DossiersLocalView> DossiersLocalView { get; set; }
        public DbSet<DossierStationnementView> DossierStationnementView { get; set; }
    }
}
