//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public Paiement()
        {
            this.Loyer = new HashSet<Loyer>();
        }
    
        public int PaiementId { get; set; }
        public System.DateTime DatePaiement { get; set; }
        public decimal MontantPaye { get; set; }
        public int ClientId { get; set; }
        public string Commentaire { get; set; }
        public int MethodePaiementId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Loyer> Loyer { get; set; }
    }
}
