//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.CodeElectronique = new HashSet<CodeElectronique>();
            this.TypeEspace = new HashSet<TypeEspace>();
        }
    
        public int SiteId { get; set; }
        public string Adresse { get; set; }
        public string Alias { get; set; }
        public int VilleId { get; set; }
    
        public virtual ICollection<CodeElectronique> CodeElectronique { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual ICollection<TypeEspace> TypeEspace { get; set; }
    }
}
