//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public int EspaceId { get; set; }
        public string Couleur { get; set; }
        public string MarqueVehicule { get; set; }
        public string PlaqueImmatriculation { get; set; }
        public string TypeVehicule { get; set; }
    
        public virtual Stationnement Stationnement { get; set; }
    }
}
