//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.Client = new HashSet<Client>();
            this.Site = new HashSet<Site>();
        }
    
        public int VilleId { get; set; }
        public string Ville1 { get; set; }
    
        public virtual ICollection<Client> Client { get; set; }
        public virtual ICollection<Site> Site { get; set; }
    }
}
