//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.CodeElectronique = new HashSet<CodeElectronique>();
            this.Contrat = new HashSet<Contrat>();
            this.Paiement = new HashSet<Paiement>();
            this.Telephone = new HashSet<Telephone>();
        }
    
        public int ClientId { get; set; }
        public bool Actif { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> VilleId { get; set; }
        public Nullable<System.DateTime> DateEntree { get; set; }
        public string Nom { get; set; }
        public string Commentaire { get; set; }
        public Nullable<int> MethodePaiementId { get; set; }
        public string Prenom { get; set; }
        public Nullable<decimal> Solde { get; set; }
    
        public virtual MethodePaiement MethodePaiement { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual ICollection<CodeElectronique> CodeElectronique { get; set; }
        public virtual ICollection<Contrat> Contrat { get; set; }
        public virtual ICollection<Paiement> Paiement { get; set; }
        public virtual ICollection<Telephone> Telephone { get; set; }
    }
}
