//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeElectronique
    {
        public int CodeId { get; set; }
        public int NoCode { get; set; }
        public string TypeCode { get; set; }
        public Nullable<int> ClientId { get; set; }
        public int SiteId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Site Site { get; set; }
    }
}
