//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrat
    {
        public int ContratId { get; set; }
        public int EspaceId { get; set; }
        public System.DateTime DateEntree { get; set; }
        public Nullable<System.DateTime> DateSortie { get; set; }
        public decimal Prix { get; set; }
        public int ClientId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Espace Espace { get; set; }
    }
}
