//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espace
    {
        public Espace()
        {
            this.Contrat = new HashSet<Contrat>();
        }
    
        public int EspaceId { get; set; }
        public int TypeEspaceId { get; set; }
        public bool Disponible { get; set; }
    
        public virtual ICollection<Contrat> Contrat { get; set; }
        public virtual Stationnement Stationnement { get; set; }
        public virtual TypeEspace TypeEspace { get; set; }
        public virtual Local Local { get; set; }
    }
}
