//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int EspaceId { get; set; }
        public string NoLocal { get; set; }
    
        public virtual Espace Espace { get; set; }
    }
}
