//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDM2.BaseDonnee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stationnement
    {
        public int EspaceId { get; set; }
        public string NoStationnement { get; set; }
        public string TypeStationnement { get; set; }
    
        public virtual Espace Espace { get; set; }
        public virtual Vehicule Vehicule { get; set; }
    }
}
